language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

addons:
    apt:
        packages:
            - openmpi-bin
            - libopenmpi-dev

install:
    - pip install --upgrade pytest pytest-mpi pytest-cov mpi4py vtk coveralls
    - pip install -e .
script:
    - pytest --cov=uvw tests
after_success:
    - coveralls
