language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

addons:
    apt:
        packages:
            - openmpi-bin
            - libopenmpi-dev

install:
    - python -m pip install --upgrade pytest pytest-mpi pytest-cov mpi4py vtk coveralls
    - python -m pip install -e .
script:
    - python -m pytest --cov-config=.coverage.cfg --cov=uvw tests
    - mpiexec -np 2 pytest tests --only-mpi
after_success:
    - coveralls
