language: python
python:
    - "3.7.9"
    - "3.8.7"
    - "3.9.7"

addons:
    apt:
        packages:
            - openmpi-bin
            - libopenmpi-dev

install:
    - python -m pip install --upgrade pytest pytest-mpi pytest-cov mpi4py vtk coveralls
    - python -m pip install -e .
script:
    - python -m pytest --cov-config=.covrc --cov=uvw tests
    - mpiexec -np 2 pytest --cov-config=.covrc --cov-append --cov=uvw tests --only-mpi
after_success:
    - coveralls
