language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

addons:
    apt:
        packages:
            - openmpi-bin
            - libopenmpi-dev

install:
    - pip install --upgrade -e .[tests]
    - pip install --upgrade coveralls
script:
    - pytest --cov=uvw tests
after_success:
    - coveralls
